### PR TITLE
Adapt content-l to full, main, and sidebar containers

### PR DESCRIPTION
**Pull request by virginiacc**
Updated -- should be ready now.

[Note: this is not quite ready to merge -- the documentation is still in progress. Just wanted to get this out to start discussion.]

Also, it breaks backward-compatibility by not using `.content-l__main`'s settings as the default -- it instead defaults to display all `.content-l_col-RATIO` classes as columns above mobile widths. I'm not entirely opposed to defaulting to `.content-l__main`, but I think there are some arguments for not doing so:
- Defaulting to columns above mobile (where columns would be expected to stack) is simpler and more general. 
- Overriding this default is single directional -- just stack `.content-l_col-RATIO` classes where you don't want them to display as columns.

Changes: 
- `.content-l_col-RATIO`s default to stacked at mobile sizes & columns above
- Add three content-l modifiers to work within three most common content containers
- Add mixins to simplify stacking `.content-l_col`s

### CODE REVIEW

**Comment by Scotchester** [comment]
Reviewed via Hangouts. All looks good! :+1:

**Comment by Scotchester** [comment]
Oops, just need a version bump in `bower.json` and a change log update.

**Comment by virginiacc** [comment]
The version info is updated -- thanks!

**Comment by Scotchester** [comment]
Excellent, thanks! Please create the Git tag and GitHub Release so you can bring it into cfgov-refresh.

**Comment by virginiacc** [comment]
Thank you!

**Pull request merged**
